language: python
sudo: false
python:
    - "2.7"
    - "3.6"
install:
    - pip install -U pip
    - python setup.py build
script:
    - pip install -r ./dev-requirements.txt
    - python setup.py build
    - python setup.py test
notifications:
    irc:
        channels: 
            - "irc.mozilla.org#services-dev"
        on_success: change
