version: 2.1

orbs:
  python: circleci/python@1.3.2

workflows:
  version: 2
  test:
    jobs:
      - python/test:
          name: "Test on Python 3.8"
          version: "3.8"
          pkg-manager: pip-dist
          args: "-r dev-requirements.txt"
          pip-dependency-file: "dev-requirements.txt"
          test-tool: pytest
